### ISSUE TITLE
Some deprecated warnings

### ISSUE THREAD

**Issue by Frenzie** [koreader/android-luajit-launcher#125]
@pazos Just noticed this while testing https://github.com/koreader/koreader-base/pull/832
```
-compile:
    [javac] Compiling 5 source files to /home/frans/src/kobo/koreader/platform/android/luajit-launcher/bin/classes
    [javac] /home/frans/src/kobo/koreader/platform/android/luajit-launcher/src/org/koreader/launcher/MainActivity.java:266: warning: [deprecation] formatIpAddress(int) in Formatter has been deprecated
    [javac]             ip_address = Formatter.formatIpAddress(ip);
    [javac]                                   ^
    [javac] /home/frans/src/kobo/koreader/platform/android/luajit-launcher/src/org/koreader/launcher/MainActivity.java:272: warning: [deprecation] formatIpAddress(int) in Formatter has been deprecated
    [javac]             gw_address = Formatter.formatIpAddress(gw);
    [javac]                                   ^
    [javac] 2 warnings
```

**Comment by pazos** [comment]
Formatter.formatIpAddress is deprecated because it doesn't support ipv6, which shouldn't hurt for WifiInfo since it will report ip and gateway as ipv4.

There are a few options, of course stack overflow has that covered too: https://stackoverflow.com/questions/20846120/alternative-for-formatter-formatipaddressint

IMO we can live with deprecation warnings unless suggested solutions provide a better/safer way of doing the same thing.

**Comment by Frenzie** [comment]
I don't much care what Android decides to deprecate at random. I was only pointing it out because you like to fix 'em. ;-)
