### ISSUE TITLE
add Storage Access Framework support in 4.4+

### ISSUE THREAD

**Issue by pazos** [koreader/android-luajit-launcher#191]
Specially for 6.0+ devices, that can allow RW permission permanently on the sdcard.

**Comment by pazos** [comment]
Errr, it turns out that SAF only allows RW storage using the saf api and doesn't allow access to the underlying filesystem api. We cannot use that in KOReader using lfs, so the only thing we can do with saf is importing documents to a place where we can have access to the filesystem.

**Comment by Frenzie** [comment]
Lovely, all very inefficient. /sigh :-)

**Comment by pazos** [comment]
Not just inefficient, but kills what KO can do in newer android devices. The "everything is a file" paradigm died on android and now begins the "everything is content".

Google/Android is pushing the following scheme:

- the user has media and documents.
- the apps have files

Any app will use MediaStorage to access media (photos|videos|music) and SAF to access documents. Apps are expected to have assets and dealing with them as they like, so they have a few paths where they can have files. Everything is deleted with the app.

And then users blame developers because some documents were lost :cry:

**Comment by Frenzie** [comment]
I still don't understand how that is even supposed to work. For example, my bank statements for 2019 are primarily a combination of PDF and CSV, with possibly other file types such as DjVu, Python, PNG, JPEG, perhaps ZIP or other archives, and maybe some personal finance app file format. So they should go together into a folder like `bank/2019`, so that if I check that folder it has everything of relevance. I don't have to care what kind of file they are.

By contrast, if something is a "PDF file" or a "CSV file," what am I even supposed to do with that?

**Comment by pazos** [comment]
> By contrast, if something is a "PDF file" or a "CSV file," what am I even supposed to do with that?

1. Get an app that handles that mimetype.
2. Open the app, grant permanent permissions on the root folder of your documents
3. Have fun reading/editing/sharing your docs as long as the app handles the SAF api.

The workflow of 2 means having a parcelable file descriptor - ie: a hard copy of the document on your app scoped storage. Once you modified the file you can save back the changes using SAF again. Then the next time you'll open your file - again with a parcelable fd - you'll get the updated one.

Leaving a few interesting ~~links~~ rants about changes in Android Q. Most of them will be enforced in Q3/4 2020 for Play Store apps, while apps distributed outside the play store won't have problems for now.


https://www.xda-developers.com/android-q-storage-access-framework-scoped-storage/

https://github.com/termux/termux-app/issues/1072, specially https://github.com/termux/termux-app/issues/1072#issuecomment-473965266

**Comment by Frenzie** [comment]
> Get an app that handles that mimetype.
> Open the app, grant permanent permissions on the root folder of your documents
> Have fun reading/editing/sharing your docs as long as the app handles the SAF api.

Yup, that sounds about as horrendously stupid as I implied.

If they want to increase my safety, just give me an easy way to designate folder access instead of the current all or nothing bs. This just makes Android worse to use at best and probably does jack shit for actual security.

I hope Android is dead by the time I need a new phone. It happened to Windows Phone, so there might be some hope…

**Comment by pazos** [comment]
> Yup, that sounds about as horrendously stupid as I implied.

Specially for document viewers, like this one.

> If they want to increase my safety, just give me an easy way to designate folder access instead of the current all or nothing bs. This just makes Android worse to use at best and probably does jack shit for actual security.

given that metadata is still available with SAF I would go for the latter.

> I hope Android is dead by the time I need a new phone. It happened to Windows Phone, so there might be some hope…

I'm not good figuring out the future of mobile os. Hell I did a few html apps for FirefoxOS in the day.

Regarding KO + SAF I won't spend a single second in figuring out how to replace mkdir, touch, ls, mv, cp (or they lfs counterparts) with something that works on top of saf. 

So the proposed solution (beyond avoid crashes on launch) is work with files in the paths that google still allows and use saf just for importing stuff.

But top priority is: do not bump targetSdk anymore. Hopefully that will allow us to run with the legacy storage model on android r,s,t,u... until the dead of Android.
