### ISSUE TITLE
Tolino frontlight button

### ISSUE THREAD

**Issue by pazos** [koreader/android-luajit-launcher#245]
From https://github.com/koreader/koreader/pull/6520#issuecomment-675547072

> I see two easy solutions. Which would you prefer?

> 1.) On Tolino we could check: We can set the intensity. If frontlight is toggled Off, we could read back the value. If the set and the read values differ, we would know, that the frontlight is toggled off. In this case we show a message to the user, that he/she should toggle it on (with the original app, or the sun symbol in the status line). Not nice for the user (we have a toggle in KOReader and a toggleButton on Android which overrules us!).

> 2.) We use the /sys/class/backlight/*/brightness-file (different path names on Epos2 and Vision4) directly. This works despite the toggleButtons on Tolino. Probably better for the user (KOReader works as expected, no need to leave the app).

I'm afraid I don't understand what you're trying to achieve. If you want to do the same thing with 1 and 2 I would go with 2 without doubt. The first sound harder to implement in a non-invasive way :).

I had the idea that you only wanted to make the button to behave correctly on KOReader, but certainly I have no idea and the whole frontlight thing is a bit annoying for me :p.

Feel free to code the thing whatever you want. I would like, if that's possible, to see the changes in this repo before submitting the changes in the frontend. Trying to review both things at the same time makes my brain hurt :)

**Comment by zwim** [comment]
The background:
It seems that the TolinoToggleButton (in Software) enables/disables the write access to brightness for `settings.system.putInt()`. If it is enabled we can do with brightness what we want, when disabled the brightness is frozen to zero. But root can write to the brightness file and change the intensity in any case.
 
> I'm afraid I don't understand what you're trying to achieve. If you want to do the same thing with 1 and 2 I would go with 2 without doubt. The first sound harder to implement in a non-invasive way :).

When going with 1 we could use the `settings.system.putInt()/getInt()` and there would be no need to deal with files (permissions). This might be a benefit for user who have installed KOReader on Tolino, but who have NOT rooted their device.
They can use brightness (but not warmth). That's why I asked for your preferences.
 
> I had the idea that you only wanted to make the button to behave correctly on KOReader, but certainly I have no idea and the whole frontlight thing is a bit annoying for me :p.

For me too, but it can be done.
About the button: First I wanted to make the toggle thing work in KOReader, which should work with #6520 in koreader/koreader. 
Then I realized the two problems mentioned there. Zero-intensity means system-intensity on generic-Android (which is easy to fix) and the Tolino problem. If we don't fix that, we will get issue request very soon ("Brightness on Tolino is broken ...")

So what do you think. Solution 1.) with `settings.system.putInt()/getInt()` and a message to the user if the TolinoSoftwareButton has to be toggled or 2.) with files (and the drawback that the Tolino has to be rooted)?

> 
> Feel free to code the thing whatever you want. I would like, if that's possible, to see the changes in this repo before submitting the changes in the frontend. Trying to review both things at the same time makes my brain hurt :)

OK, that is fine with me.
I will just wait until #244 gets merged, as the Tolino fix might interfere with #244.

**Comment by pazos** [comment]
> When going with 1 we could use the settings.system.putInt()/getInt() and there would be no need to deal with files (permissions). This might be a benefit for user who have installed KOReader on Tolino, but who have NOT rooted their device.
They can use brightness (but not warmth). That's why I asked for your preferences.

My preference is leaving this to you :).  If you think it worths your time feel free to implement it. Sounds good :+1:

**Comment by zwim** [comment]
I think about it and I will do that on the weekend.
