### ISSUE TITLE
[FR] add exception handling after JNI calls

### ISSUE THREAD

**Issue by ildar** [koreader/android-luajit-launcher#277]
Currently all JNI calls made unchecked. The checked call demo:
``` lua
function test1(name)
  return android.jni:context(android.app.activity.vm, function(jni)
    local clz, e = jni.env[0].FindClass(jni.env, name), jni.env[0].ExceptionCheck(jni.env)
    if e == 0 then
      e = nil
    else
      local ex = jni.env[0].ExceptionOccurred(jni.env)
      jni.env[0].ExceptionClear(jni.env)
      e = jni:to_string(
        jni:callObjectMethod(ex, "getMessage", "()Ljava/lang/String;")
        )
    end
    return clz, e
  end)
end
local clzz, e = test1("java/lang/WRONGNAME")
if e then
  print(e)
end
```

**Comment by pazos** [comment]
Not interested

**Comment by Frenzie** [comment]
Is this related to anything in particular? As illustrated quite well by the demo above this has never been an issue, unlike some other stuff like ANR.

**Comment by ildar** [comment]
I see a big gap with the android-luajit-launcher reception: you treat it as
just one gear of the KOReader that carries its function: start and
serve KR on Android platform. I treat it as an Android NativeActivity based
launcher for LuaJIT, implementing the main loop within Lua land via FFI.
That also allows running other (different) Lua apps in Android env.
As the result I just annoy you with non-KR related ideas. Right? Then it's
time for me just to move away.

**Comment by Frenzie** [comment]
> I treat it as an Android NativeActivity based
launcher for LuaJIT, implementing the main loop within Lua land via FFI. [...] As the result I just annoy you with non-KR related ideas. Right? Then it's
time for me just to move away.

No, not at all! That's exactly what this repo is for.

But I would assume you ran into an actual problem, because otherwise this seems fairly random to me. The example above is broken code that should be fixed. At the very least it sounds like a good addition. I'm just curious to know if there's a natural example that doesn't involve broken code.

**Comment by pazos** [comment]
> As the result I just annoy you with non-KR related ideas. Right? Then it's time for me just to move away.

Not interested doesn't mean annoyed. PRs are welcome for stuff that doesn't relate to KOReader. But in this case is not a PR, but a feature request which doesn't serve any purpose.

To call java from lua you'll need to know:

1. the name of the class
2. the name of the method
3. the type of the method
4. method's signature

Any typo or mismatch in any element would make your code crash. And because lua is dynamically typed luacheck won't alert you as both "()Ljava/lang/String;" and "()Ljava/io/File;" are valid lua strings, but one is a valid signature for the method `"getMessage"` and the other is not.

The same happens when you're checking exceptions: you call `jni:callObjectMethod`. If you call `jni:callStaticObjectMethod` you'll trigger an error, because there isn't any static method which returns an object named "getMessage" for the class `ex`.

Catching JNI exceptions isn't a bad thing to add, but to serve a purpose it needs to thow the exception and interrupt the app flow, so the result would be exactly the same: a crash, but the way to retrieve the bug would be better as it would be associated to the app name and not a RuntimeError (mismatch signature) or a native crash (LuaJIT error dealing with libraries using FFI)

**Comment by pazos** [comment]
`jni.env[0].FindClass(jni.env, name)` is a cool stuff if you're implementing method invokation via reflection, because the name of the class in that case is not part of the API, as you'll need to know if there is available on a given device. In that case makes sense to check exceptions before calling the method.

**Comment by Frenzie** [comment]
> Any typo or mismatch in any element would make your code crash. And because lua is dynamically typed luacheck won't alert you as both "()Ljava/lang/String;" and "()Ljava/io/File;" are valid lua strings, but one is a valid signature for the method "getMessage" and the other is not.

Yup, that's exactly what I meant by broken code.

**Comment by Codereamp** [comment]
While agreeing in general than the process of finding the correct names, signatures, parameters with JNI is the sole responsibilities of the developer who tries to implement something specific for Android, there are cases when the necessity for  catch Java exception is about the internal Android logic. 

I will explain my case but not in order to encourage to reopen the issue (there are still better things to apply the developers' time to), but in order to add a little "how to" for those who would like to control exceptions in jni/ffi/lua code. I myself found this discussion just by googling [ "ExceptionCheck" "Lua" "ffi" ] so someone might find it useful in the future

My goal is to set a system setting on Android. While KOReader has the "Modify system settings" permission request in the manifest, it can be switched off either by default or by the user. If the permission setting if off and I rely on the default mechanics of android.lua module then the following call

```
jni:callStaticBooleanMethod(
    "android/provider/Settings$System",
    "putInt",
    "(Landroid/content/ContentResolver;Ljava/lang/String;I)Z",
    arg_object,
    arg_name,
    arg_value
)
```
will throw a Java exception and the UI will show a cryptic screen about an uncatched exception with an except from logcat. 

But to apply the ExceptionCheck logic that is explained as the primary way to catch Java exceptions in jni code, the ExceptionCheck->ExceptionDescribe->ExceptionClear calls should be made right after the call in question so the following default implementation

```
function JNI:callStaticBooleanMethod(class, method, signature, ...)
    local clazz = self.env[0].FindClass(self.env, class)
    local methodID = self.env[0].GetStaticMethodID(self.env, clazz, method, signature)
    local res = self.env[0].CallStaticBooleanMethod(self.env, clazz, methodID, ...)
    self.env[0].DeleteLocalRef(self.env, clazz)
    return res == C.JNI_TRUE
end
```
can't be used for ExceptionCheck because it probably contains DeleteLocalRef call, so I had to reimplement it to something like

```
function JniChecked_CallStaticBooleanMethod(jni, class, method, signature, ...)
    local clazz = jni.env[0].FindClass(jni.env, class)
    local methodID = jni.env[0].GetStaticMethodID(jni.env, clazz, method, signature)
    local res = jni.env[0].CallStaticBooleanMethod(jni.env, clazz, methodID, ...)

    ExceptionOccured = JniExceptCheck(jni)

    jni.env[0].DeleteLocalRef(jni.env, clazz)

    if ExceptionOccured then
      res = false
    end  

    return res, ExceptionOccured
end

```
that allowed be to gracefully show a InfoMessage message
(here JniExceptCheck is my own function that does all the necessary step to detect and clear the exception)

As a side note, KOReader itself uses the android.permission.WRITE_SETTINGS to control the screen_off_timeout setting, but the code is int the Java/Kotlin files so it's easy to try except it  (what KOReader successfully does)
