### ISSUE TITLE
Onyx: cpu sleeps on idle

### ISSUE THREAD

**Issue by pazos** [koreader/android-luajit-launcher#395]
I've just installed KOreader on my new Onyx Boox Nova Air 2. The Nova Air 2 is _theoretically_ identical to the Nova Air 1 with Android 11 and an upgraded processor, and it mostly works the same, but I've noticed that if there are more than about 300 books uploaded to the home folder, the device is noticeably slow to navigate to that folder, and the app starts very slowly. Once I hit about 1200 books (the size of my library) the device needs about 60 seconds to start after an exit.

KOreader also enables color when first started, which the Air 2 doesn't support.

Other than that, KOreader seems to work fine on this device.

Please let me know if I can send you any data or perform any useful tests!

_Originally posted by @randbrittain in https://github.com/koreader/koreader/issues/8482#issuecomment-1331412045_

**Comment by pazos** [comment]
affects onyx tab ultra and onyx boox air 2.

**Comment by randbrittain** [comment]
I tried this with the latest nightly (2022-12-09) and there was no improvement. If anything, the problem is worse. After the app loads, there's a noticeable delay of several seconds before the DPI adjusts to the selected level. Attached are logs from a Nova Air 2.
[logcat.txt](https://github.com/koreader/android-luajit-launcher/files/10201418/logcat.txt)

**Comment by pazos** [comment]
Fixed by the borked company
